### ISSUE TITLE
Wrong directory in README.md

### ISSUE THREAD

**Issue by szymonmatuszczak** [devbisme/WireIt#8]
Probably it should be /usr/share/kicad/scripting/plugins instead of current kicad/share/kicad/scripting/plugins.

**Comment by xesscorp** [comment]
I corrected this. Thanks.

**Comment by szymonmatuszczak** [comment]
It is still wrong. It's /usr/share/kicad/scripting/plugins, not kicad/scripting/plugins nor kicad/share/kicad/scripting/plugins.
